runtime: nodejs12
env: standard
# handlers:
# # Serve all static files with url ending with a file extension
# - url: /(...+)$
#   static_files: build/\1
#   upload: build/(...+)$
# # Catch all handler to index.html
# - url: /.*
#   static_files: build/index.html
#   upload: build/index.html
#   redirect_http_response_code: 301
#   script: auto

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html